version: 0.2

env:
  secrets-manager:
    SECRET_USERNAME: "docker-credentials:username"
    SECRET_PASSWORD: "docker-credentials:password"

phases:
  pre_build:
    commands:
      - echo Logging in to DockerHun
      - echo "$SECRET_PASSWORD" | docker login -u "$SECRET_USERNAME" --password-stdin

  build:
    commands:
      - echo "Building Docker Image"
      - docker build -t roccomercuri1/pottery-db:latest .
        # add --platform linux/arm64  after build for mac silicon

  post_build:
    commands:
      - echo "Pushing Docker Image..."
      - docker push roccomercuri1/pottery-db:latest .

artifacts:
  files:
    - Dockerfile
